# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jonathan/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Created by `pipx` on 2024-02-22 02:41:22
export PATH="$PATH:/home/jonathan/.local/bin"

autoload -U bashcompinit
bashcompinit

eval "$(register-python-argcomplete pipx)"
